### ISSUE TITLE
Unit Test Failure: cell_area_positive

### ISSUE THREAD

**Issue by RichardVasquez** [RichardVasquez/h3net#2]
TestSuite.TestH3CellAreaExhaustive.cell_area_positive

  Expected: greater than 0.0d
  But was:  NaN

   at TestSuite.TestH3CellAreaExhaustive.cell_area_assert(H3Index cell) in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\TestH3CellAreaExhaustive.cs:line 73
   at TestSuite.Lib.Utility.IterateBaseCellIndexesAtRes(Int32 res, Action`1 callback, Int32 baseCell) in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\Lib\Utility.cs:line 51
   at TestSuite.Lib.Utility.IterateAllIndexesAtResPartial(Int32 res, Action`1 callback, Int32 baseCells) in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\Lib\Utility.cs:line 35
   at TestSuite.Lib.Utility.IterateAllIndexesAtRes(Int32 res, Action`1 callback) in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\Lib\Utility.cs:line 20
   at TestSuite.TestH3CellAreaExhaustive.cell_area_positive() in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\TestH3CellAreaExhaustive.cs:line 120

**Comment by RichardVasquez** [comment]
Fixed by modifying Constants.H3.DBL_EPSILON to a more forgiving value.  It looks like C# may have a higher margin of inaccuracy in its trig functions as implied here:  https://github.com/dotnet/runtime/issues/8528

Until this gets updated with a high precision trig library,l I'm willing to work with the lower accuracy.
