### ISSUE TITLE
Unite Test Failure: h3UniEdgeBoundary

### ISSUE THREAD

**Issue by RichardVasquez** [RichardVasquez/h3net#3]
Expected: 2
  But was:  3

   at TestSuite.TestH3UniEdgeExhaustive.H3UniEdgeBoundaryAssertions(H3Index h3) in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\TestH3UniEdgeExhaustive.cs:line 55
   at TestSuite.Lib.Utility.IterateBaseCellIndexesAtRes(Int32 res, Action`1 callback, Int32 baseCell) in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\Lib\Utility.cs:line 51
   at TestSuite.Lib.Utility.IterateAllIndexesAtResPartial(Int32 res, Action`1 callback, Int32 baseCells) in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\Lib\Utility.cs:line 35
   at TestSuite.Lib.Utility.IterateAllIndexesAtRes(Int32 res, Action`1 callback) in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\Lib\Utility.cs:line 20
   at TestSuite.TestH3UniEdgeExhaustive.h3UniEdgeBoundary() in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\TestH3UniEdgeExhaustive.cs:line 90

**Comment by RichardVasquez** [comment]
This is fixed with a typo and some fixed logic.  Currently in another branch, but will be merged in soon.
