### ISSUE TITLE
Unit Test Failure: FillIndex

### ISSUE THREAD

**Issue by RichardVasquez** [RichardVasquez/h3net#4]
h: 0801dfffffffffff
nextRes: 1
currentRes: 0
  Expected: 6
  But was:  5

   at TestSuite.TestPolyfill.fillIndex_assertions(H3Index h) in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\TestPolyfill.cs:line 114
   at TestSuite.Lib.Utility.IterateBaseCellIndexesAtRes(Int32 res, Action`1 callback, Int32 baseCell) in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\Lib\Utility.cs:line 51
   at TestSuite.Lib.Utility.IterateAllIndexesAtResPartial(Int32 res, Action`1 callback, Int32 baseCells) in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\Lib\Utility.cs:line 35
   at TestSuite.Lib.Utility.IterateAllIndexesAtRes(Int32 res, Action`1 callback) in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\Lib\Utility.cs:line 20
   at TestSuite.TestPolyfill.FillIndex() in C:\Users\catch\Documents\JetBrainsGitHub\h3\Tests\NUnit\H3Suite\TestPolyfill.cs:line 338

**Comment by RichardVasquez** [comment]
Fixed with accuracy branch to be merged in soon.
